### PR TITLE
Trying to add time slider

### PR DESCRIPTION
**Pull request by rkpalmerjr**
Just commented out for now.  Not having much success.  Just trying to get the slider to  be created at this point.  Not even tied to data.

### CODE REVIEW

**Comment by bryangarner** [comment]
noticed a couple of issues wanted to point out.
The map is no longer full screen, it appears there is a 10px margin around the entire map frame.
The icon for the filter became uncentered somehow.
When doing a search and clearing a search there is a console error about the layers not being found.

Just want to keep a note of these issues so we can fix them in the future.

**Comment by rkpalmerjr** [comment]
Ok I'll take a look this evening.  I've made some other changes since then but didn't post anything back up yet because I wasn't having much luck getting the things I was trying to do to work.  I'll post something back up this evening.

**Comment by bryangarner** [comment]
okay thank you Kevin!! hope you had a good weekend

**Comment by rkpalmerjr** [comment]
Ok so that's what Bootstrap was for...

**Pull request merged**
